version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/source/agent/addons/quic/test"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/source/agent/quic"
    schedule:
      interval: "monthly"