[portal]
keystorePath = "./cert/certificate.pfx"
hostname = "" #default: ""
ip_address = "" #default: ""
# Port that the socket.io server listens at.
port = 8080 #default: 8080
ssl = true #default: true
force_tls_v12 = false #default: false, tls1 and tls1.1 will not be allowed if set to true
#The network inferface the socket.io will be bound to in case portal.ip_address (the 'ip_address' item above) is not specified or equal to "".
# networkInterface = "eth1"
# How many seconds before Socket.IO client sending a new ping packet. This value might be overwrote by client side.
# ping_interval = 25 #default: undefined
# How many seconds without a pong packet to consider the Socket.IO connection closed. This value might be overwrote by client side.
# ping_timeout = 60 #default: undefined
# Life time for reconnection ticket. Unit: second.
reconnection_ticket_lifetime = 600 #default: 600
# Client will leave conference if it cannot reconnect to Socket.IO server after |reconnection_timeout| seconds.
reconnection_timeout = 60 #default: 60


[cluster]
name = "woogeen-cluster"

#The number of times to retry joining if the first try fails.
join_retry = 60 #default: 60

#The interval of reporting the work load
report_load_interval = 1000 #default: 1000, unit: millisecond

#The max CPU load under which this worker can taks new tasks.
max_load = 0.85 #default: 0.85


[capacity]
#The ISP list this portal tends to handle
isps = [] #default: [], which means all ISPs.
#The region list this portal tends to handle
regions = [] #default: [], which means all regions.


[rabbit]
host = "localhost" #default: "localhost"
port = 5672 #default: 5672

[mongo]
dataBaseURL = "localhost/owtdb" #default: "localhost/owtdb"
