[portal]
#Default and max video bandwidth parameters to be used by clients
keystorePath = "./cert/certificate.pfx"
hostname = "" #default: ""
ip_address = "" #default: ""
port = 8080 #default: 8080
ssl = true #default: true
limit_n_rooms = 20 #default: 20
warning_n_rooms = 15 #default: 15
#Use the name of the inferface you want to bind to for socket.io
# networkInterface = "eth1"

#Roles to be used by services
[portal.roles.presenter]
publish = true
record = true
subscribe = true

[portal.roles.viewer]
subscribe = true

[portal.roles.viewerWithData]
subscribe = true

[portal.roles.viewerWithData.publish]
audio = false
data = true
screen = false
video = false

[cluster]
#The name of the cluster to join.
name = "woogeen-cluster"
#The number of times to try joining
join_retry = 5 #default: 5
#The interval of retrying joining.
join_interval = 3000 #default: 3000, unit: millisecond
#The interval of retrying recovering the membership to the cluster.
recover_interval = 1000 #default: 1000, unit: millisecond
#The interval of sending keepAlive messages.
keep_alive_interval = 1000 #default: 1000, unit: millisecond
#The interval of reporting the work load
report_load_interval = 1000 #default: 1000, unit: millisecond
#The max work load this worker can take.
max_load = 0.85 #default: 0.85
#Network max scale to calculate network usage percentage
network_max_scale = 1000 #unit: Mbps

[rabbit]
host = "localhost" #default: "localhost"
port = 5672 #default: 5672
