[portal]
keystorePath = "./cert/certificate.pfx"
hostname = "" #default: ""
ip_address = "" #default: ""
# Port that the socket.io server listens at.
port = 8080 #default: 8080
# Port that the REST server listens at.
rest_port = 8081 #default: 8081
ssl = true #default: true
#The network inferface the socket.io will be bound to in case portal.ip_address (the 'ip_address' item above) is not specified or equal to "".
# networkInterface = "eth1"

#Roles defined in services
# NOTE: Each of the roles is defined in a tree-level structure and must comply with the following rules:
# 1) the ROLE level, are key-value pairs representing the role name and its operation scope, in which the keys must be strings such as the 'admin'/'presenter'/'viewer'... demonstrated as follow, and the values must be the OPERATION level objects.
# 2) the OPERATION level, are key-value pairs representing the operation set the role is allowed to perform, in which the keys must be among the list of ['publish', 'subscribe', 'record', 'text'], and the values must be either literally true, false or OBJECT level objects. The default value is false for 'publish', 'subscribe' and 'record', and true for 'text' if not specified.
# 3) the OBJECT level, are key-value pairs representing the media the operation can be performed upon, in which the keys must be in the list of ['audio', 'video', 'screen'], and the values must be either literally true or false. The default value is false if not specified.
[portal.roles.admin]
publish = true
record = true
subscribe = true
addExternalOutput = true

[portal.roles.presenter]
publish = true
record = true
subscribe = true
addExternalOutput = true

[portal.roles.audio_only_presenter.publish]
audio = true
[portal.roles.audio_only_presenter.subscribe]
audio = true

[portal.roles.viewer]
subscribe = true

[portal.roles.video_only_viewer.subscribe]
video = true

[portal.roles.no_text_viewer]
subscribe = true
text = false

[cluster]
name = "woogeen-cluster"

#The number of times to retry joining if the first try fails.
join_retry = 5 #default: 5

#The interval of retrying recovering the connection to the cluster.
recover_interval = 1000 #default: 1000, unit: millisecond

#The interval of sending keepAlive messages.
keep_alive_interval = 1000 #default: 1000, unit: millisecond

#The interval of reporting the work load
report_load_interval = 1000 #default: 1000, unit: millisecond

#The max work load this worker can carry.
max_load = 0.85 #default: 0.85

[rabbit]
host = "localhost" #default: "localhost"
port = 5672 #default: 5672
