{
  'targets': [{
    'target_name': 'webrtc-quic',
    'sources':[
      'addon.cc',
      '../webrtcLib/ThreadPool.cc',
      '../webrtcLib/IOThreadPool.cc',
      'RTCIceTransport.cc',
      'RTCIceCandidate.cc',
      'RTCQuicTransport.cc',
      'RTCQuicTransportBase.cc',
      'RTCCertificate.cc',
      'P2PQuicTransport.cc',
      'IceConnectionAdapter.cc',
      'QuicConnectionAdapter.cc',
      'QuicStream.cc',
      '../../../../third_party/licode/erizo/src/erizo/LibNiceConnection.cpp',
      '../../../../third_party/licode/erizo/src/erizo/IceConnection.cpp',
      '../../../../third_party/licode/erizo/src/erizo/lib/LibNiceInterfaceImpl.cpp',
      '../../../../third_party/licode/erizo/src/erizo/thread/IOThreadPool.cpp',
      '../../../../third_party/licode/erizo/src/erizo/thread/IOWorker.cpp',
      '../../../../third_party/licode/erizo/src/erizo/thread/Scheduler.cpp',
      '../../../../third_party/licode/erizo/src/erizo/thread/ThreadPool.cpp',
      '../../../../third_party/licode/erizo/src/erizo/thread/Worker.cpp',
      '../../../core/owt_base/MediaFramePipeline.cpp',
      '../../../core/owt_base/MediaFrameMulticaster.cpp',
    ],
    'defines':[
      'OWT_ENABLE_QUIC=1',
      'GOOGLE_PROTOBUF_NO_RTTI',
    ],
    'cflags_cc': ['-std=c++14', '-fexceptions', '-DWEBRTC_POSIX', '-DWEBRTC_LINUX', '-DLINUX', '-DNOLINUXIF', '-DNO_REG_RPC=1', '-DHAVE_VFPRINTF=1', '-DRETSIGTYPE=void', '-DNEW_STDIO', '-DHAVE_STRDUP=1', '-DHAVE_STRLCPY=1', '-DHAVE_LIBM=1', '-DHAVE_SYS_TIME_H=1', '-DTIME_WITH_SYS_TIME_H=1'],
    'include_dirs': [
      "<!(node -e \"require('nan')\")",
      'conn_handler',
      '../../../../third_party/licode/erizo/src/erizo',
      '../../../../third_party/licode/erizo/src/erizo/lib',
      '../../../../third_party/licode/erizo/src/erizo/thread',
      '../../../../third_party/licode/erizo/src/erizo/stats',
      '../../../core/common',
      '../../../core/owt_base',
      '../../../../build/libdeps/build/include',
      '<!@(pkg-config glib-2.0 --cflags-only-I | sed s/-I//g)',
      '$(CHROMIUM_HOME)',
      '$(CHROMIUM_HOME)/third_party/webrtc',
      '$(CHROMIUM_HOME)/third_party/abseil-cpp',
      '$(CHROMIUM_HOME)/third_party/boringssl/src/include',
      '$(CHROMIUM_HOME)/out/gcc/gen',
      '$(CHROMIUM_HOME)/third_party/protobuf/src',
    ],
    'ldflags': [
      '-Wl,--no-as-needed',
      '-Wl,-rpath,$(CHROMIUM_HOME)/out/gcc',
      '-L$(CORE_HOME)/../../build/libdeps/build/lib',
      '-L$(CHROMIUM_HOME)/out/gcc',
      '-L$(CHROMIUM_HOME)/out/gcc/obj/third_party/webrtc/rtc_base',
      '-L$(CHROMIUM_HOME)/out/gcc/obj/net',
      #'-L$(CHROMIUM_HOME)/out/gcc/obj/third_party/boringssl',
    ],
    'cflags_cc!': [
      '-std=gnu++0x',
      '-fno-exceptions',
    ],
    'libraries': [
      '-ldl',
      '-llog4cxx',
      '-lboost_thread',
      '-lboost_system',
      '-lnice',
      '-lbase',
      '-lnet_quic',
      '-lrtc_base_complete',
      '-lboringssl',
    ],
    'include_dirs!':[
      '<(node_root_dir)/deps/openssl/config',
      '<(node_root_dir)/deps/openssl/openssl/include',
    ],
  }]
}
