[agent]
#Max processes that agent can run
maxProcesses = 13 #default: 13

#Number of precesses that agent runs when it starts. 1 <= prerunProcesses <= maxProcesses.
prerunProcesses = 2 #default: 2


[cluster]
name = "woogeen-cluster"

#The number of times to retry joining if the first try fails.
join_retry = 60 #default: 60

#The interval of sending keepAlive messages.
keep_alive_interval = 800 #default: 800, unit: millisecond

#The interval of reporting the work load
report_load_interval = 1000 #default: 1000, unit: millisecond

#The max work load this worker can take.
max_load = 0.85 #default: 0.85


[rabbit]
host = "localhost" #default: "localhost"
port = 5672 #default: 5672

[internal]
# sctp/tcp available, sctp is default
protocol = "sctp"
