[agent]
#Max processes that agent can run
maxProcesses = 13 #default: 13

#Number of precesses that agent runs when it starts. 1 <= prerunProcesses <= maxProcesses.
prerunProcesses = 2 #default: 2

[nuve]
dataBaseURL = "localhost/nuvedb" #default: "localhost/nuvedb"

#Roles defined in services
# NOTE: Each of the roles is defined in a tree-level structure and must comply with the following rules:
# 1) the ROLE level, are key-value pairs representing the role name and its operation scope, in which the keys must be strings such as the 'admin'/'presenter'/'viewer'... demonstrated as follow, and the values must be the OPERATION level objects.
# 2) the OPERATION level, are key-value pairs representing the operation set the role is allowed to perform, in which the keys must be among the list of ['publish', 'subscribe', 'record', 'text'], and the values must be either literally true, false or OBJECT level objects. The default value is false for 'publish', 'subscribe' and 'record', and true for 'text' if not specified.
# 3) the OBJECT level, are key-value pairs representing the media the operation can be performed upon, in which the keys must be in the list of ['audio', 'video', 'screen'], and the values must be either literally true or false. The default value is false if not specified.
[session.roles.admin]
publish = true
record = true
subscribe = true
addExternalOutput = true
# The 'manage' operation includes mute/unmute users and change users' permissions in same room
manage = true

[session.roles.presenter]
publish = true
record = true
subscribe = true
addExternalOutput = true

[session.roles.audio_only_presenter.publish]
audio = true
[session.roles.audio_only_presenter.subscribe]
audio = true

[session.roles.viewer]
subscribe = true

[session.roles.video_only_viewer.subscribe]
video = true

[session.roles.no_text_viewer]
subscribe = true
text = false

[cluster]
name = "woogeen-cluster"

#The number of times to retry joining if the first try fails.
join_retry = 60 #default: 60

#The interval of reporting the work load
report_load_interval = 1000 #default: 1000, unit: millisecond

#The max work load this worker can take.
max_load = 0.85 #default: 0.85


[rabbit]
host = "localhost" #default: "localhost"
port = 5672 #default: 5672

[internal]
# tcp/sctp available, tcp is default
protocol = "tcp"
