(function(d,a){d.version="0.9.6";d.protocol=1;d.transports=[];d.j=[];d.sockets={};d.connect=function(b,c){var e=d.util.parseUri(b),f,i;a&&a.location&&(e.protocol=e.protocol||a.location.protocol.slice(0,-1),e.host=e.host||(a.document?a.document.domain:a.location.hostname),e.port=e.port||a.location.port);f=d.util.uniqueUri(e);var h={host:e.host,secure:"https"==e.protocol,port:e.port||("https"==e.protocol?443:80),query:e.query||""};d.util.merge(h,c);if(h["force new connection"]||!d.sockets[f])i=new d.Socket(h);
!h["force new connection"]&&i&&(d.sockets[f]=i);i=i||d.sockets[f];return i.of(1<e.path.length?e.path:"")}})("object"===typeof module?module.exports:this.io={},this);
(function(d,a){var b=d.util={},c=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,e="source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(",");b.parseUri=function(a){for(var a=c.exec(a||""),b={},g=14;g--;)b[e[g]]=a[g]||"";return b};b.uniqueUri=function(b){var c=b.protocol,g=b.host,b=b.port;"document"in
a?(g=g||document.domain,b=b||("https"==c&&"https:"!==document.location.protocol?443:document.location.port)):(g=g||"localhost",!b&&"https"==c&&(b=443));return(c||"http")+"://"+g+":"+(b||80)};b.query=function(a,c){var g=b.chunkQuery(a||""),e=[];b.merge(g,b.chunkQuery(c||""));for(var f in g)g.hasOwnProperty(f)&&e.push(f+"="+g[f]);return e.length?"?"+e.join("&"):""};b.chunkQuery=function(a){for(var b={},a=a.split("&"),c=0,e=a.length,f;c<e;++c)f=a[c].split("="),f[0]&&(b[f[0]]=f[1]);return b};var f=!1;
b.load=function(c){if("document"in a&&"complete"===document.readyState||f)return c();b.on(a,"load",c,!1)};b.on=function(a,b,c,f){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener&&a.addEventListener(b,c,f)};b.request=function(a){if(a&&"undefined"!=typeof XDomainRequest)return new XDomainRequest;if("undefined"!=typeof XMLHttpRequest&&(!a||b.ua.hasCORS))return new XMLHttpRequest;if(!a)try{return new (window[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(c){}return null};"undefined"!=
typeof window&&b.load(function(){f=!0});b.defer=function(a){if(!b.ua.webkit||"undefined"!=typeof importScripts)return a();b.load(function(){setTimeout(a,100)})};b.merge=function(a,c,g,f){var f=f||[],g="undefined"==typeof g?2:g,e;for(e in c)c.hasOwnProperty(e)&&0>b.indexOf(f,e)&&("object"!==typeof a[e]||!g?(a[e]=c[e],f.push(c[e])):b.merge(a[e],c[e],g-1,f));return a};b.mixin=function(a,c){b.merge(a.prototype,c.prototype)};b.inherit=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c};
b.isArray=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};b.intersect=function(a,c){for(var g=[],e=a.length>c.length?a:c,f=a.length>c.length?c:a,d=0,r=f.length;d<r;d++)~b.indexOf(e,f[d])&&g.push(f[d]);return g};b.indexOf=function(a,b,c){for(var f=a.length,c=0>c?0>c+f?0:c+f:c||0;c<f&&a[c]!==b;c++);return f<=c?-1:c};b.toArray=function(a){for(var b=[],c=0,f=a.length;c<f;c++)b.push(a[c]);return b};b.ua={};b.ua.hasCORS="undefined"!=typeof XMLHttpRequest&&function(){try{var a=
new XMLHttpRequest}catch(b){return!1}return void 0!=a.withCredentials}();b.ua.webkit="undefined"!=typeof navigator&&/webkit/i.test(navigator.userAgent)})("undefined"!=typeof io?io:module.exports,this);
(function(d,a){function b(){}d.EventEmitter=b;b.prototype.on=function(b,e){this.$events||(this.$events={});this.$events[b]?a.util.isArray(this.$events[b])?this.$events[b].push(e):this.$events[b]=[this.$events[b],e]:this.$events[b]=e;return this};b.prototype.addListener=b.prototype.on;b.prototype.once=function(a,b){function f(){d.removeListener(a,f);b.apply(this,arguments)}var d=this;f.listener=b;this.on(a,f);return this};b.prototype.removeListener=function(b,e){if(this.$events&&this.$events[b]){var f=
this.$events[b];if(a.util.isArray(f)){for(var d=-1,h=0,g=f.length;h<g;h++)if(f[h]===e||f[h].listener&&f[h].listener===e){d=h;break}if(0>d)return this;f.splice(d,1);f.length||delete this.$events[b]}else(f===e||f.listener&&f.listener===e)&&delete this.$events[b]}return this};b.prototype.removeAllListeners=function(a){this.$events&&this.$events[a]&&(this.$events[a]=null);return this};b.prototype.listeners=function(b){this.$events||(this.$events={});this.$events[b]||(this.$events[b]=[]);a.util.isArray(this.$events[b])||
(this.$events[b]=[this.$events[b]]);return this.$events[b]};b.prototype.emit=function(b){if(!this.$events)return!1;var e=this.$events[b];if(!e)return!1;var f=Array.prototype.slice.call(arguments,1);if("function"==typeof e)e.apply(this,f);else if(a.util.isArray(e))for(var e=e.slice(),d=0,h=e.length;d<h;d++)e[d].apply(this,f);else return!1;return!0}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(d,a){function b(a){return 10>a?"0"+a:a}function c(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var b=n[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function e(a,f){var d,i,h,n,o=g,s,p=f[a];p instanceof Date&&(p=isFinite(a.valueOf())?a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"Z":null);"function"===typeof l&&(p=l.call(f,a,
p));switch(typeof p){case "string":return c(p);case "number":return isFinite(p)?""+p:"null";case "boolean":case "null":return""+p;case "object":if(!p)return"null";g+=k;s=[];if("[object Array]"===Object.prototype.toString.apply(p)){n=p.length;for(d=0;d<n;d+=1)s[d]=e(d,p)||"null";h=0===s.length?"[]":g?"[\n"+g+s.join(",\n"+g)+"\n"+o+"]":"["+s.join(",")+"]";g=o;return h}if(l&&"object"===typeof l){n=l.length;for(d=0;d<n;d+=1)"string"===typeof l[d]&&(i=l[d],(h=e(i,p))&&s.push(c(i)+(g?": ":":")+h))}else for(i in p)Object.prototype.hasOwnProperty.call(p,
i)&&(h=e(i,p))&&s.push(c(i)+(g?": ":":")+h);h=0===s.length?"{}":g?"{\n"+g+s.join(",\n"+g)+"\n"+o+"}":"{"+s.join(",")+"}";g=o;return h}}if(a&&a.parse)return d.JSON={parse:a.parse,stringify:a.stringify};var f=d.JSON={},i=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,k,n={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f",
"\r":"\\r",'"':'\\"',"\\":"\\\\"},l;f.stringify=function(a,b,c){var f;k=g="";if("number"===typeof c)for(f=0;f<c;f+=1)k+=" ";else"string"===typeof c&&(k=c);if((l=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return e("",{"":a})};f.parse=function(a,b){function c(a,f){var g,d,e=a[f];if(e&&"object"===typeof e)for(g in e)Object.prototype.hasOwnProperty.call(e,g)&&(d=c(e,g),void 0!==d?e[g]=d:delete e[g]);return b.call(a,f,e)}var f,a=""+a;i.lastIndex=
0;i.test(a)&&(a=a.replace(i,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+a+")"),"function"===typeof b?c({"":f},""):f;throw new SyntaxError("JSON.parse");}})("undefined"!=typeof io?io:module.exports,"undefined"!==typeof JSON?JSON:void 0);
(function(d,a){var b=d.parser={},c=b.packets="disconnect,connect,heartbeat,message,json,event,ack,error,noop".split(","),e=b.reasons=["transport not supported","client not handshaken","unauthorized"],f=b.advice=["reconnect"],i=a.JSON,h=a.util.indexOf;b.encodePacket=function(a){var b=h(c,a.type),g=a.id||"",d=a.endpoint||"",q=a.ack,t=null;switch(a.type){case "error":var u=a.reason?h(e,a.reason):"",a=a.advice?h(f,a.advice):"";if(""!==u||""!==a)t=u+(""!==a?"+"+a:"");break;case "message":""!==a.data&&
(t=a.data);break;case "event":t={name:a.name};a.args&&a.args.length&&(t.args=a.args);t=i.stringify(t);break;case "json":t=i.stringify(a.data);break;case "connect":a.qs&&(t=a.qs);break;case "ack":t=a.ackId+(a.args&&a.args.length?"+"+i.stringify(a.args):"")}b=[b,g+("data"==q?"+":""),d];null!==t&&void 0!==t&&b.push(t);return b.join(":")};b.encodePayload=function(a){var b="";if(1==a.length)return a[0];for(var c=0,f=a.length;c<f;c++)b+="\ufffd"+a[c].length+"\ufffd"+a[c];return b};var g=/([^:]+):([0-9]+)?(\+)?:([^:]+)?:?([\s\S]*)?/;
b.decodePacket=function(a){var b=a.match(g);if(!b)return{};var d=b[2]||"",a=b[5]||"",h={type:c[b[1]],endpoint:b[4]||""};d&&(h.id=d,h.ack=b[3]?"data":!0);switch(h.type){case "error":b=a.split("+");h.reason=e[b[0]]||"";h.advice=f[b[1]]||"";break;case "message":h.data=a||"";break;case "event":try{var q=i.parse(a);h.name=q.name;h.args=q.args}catch(t){}h.args=h.args||[];break;case "json":try{h.data=i.parse(a)}catch(u){}break;case "connect":h.qs=a||"";break;case "ack":if(b=a.match(/^([0-9]+)(\+)?(.*)/))if(h.ackId=
b[1],h.args=[],b[3])try{h.args=b[3]?i.parse(b[3]):[]}catch(x){}}return h};b.decodePayload=function(a){if("\ufffd"==a.charAt(0)){for(var c=[],f=1,g="";f<a.length;f++)"\ufffd"==a.charAt(f)?(c.push(b.decodePacket(a.substr(f+1).substr(0,g))),f+=Number(g)+1,g=""):g+=a.charAt(f);return c}return[b.decodePacket(a)]}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(d,a){function b(a,b){this.socket=a;this.sessid=b}d.Transport=b;a.util.mixin(b,a.EventEmitter);b.prototype.onData=function(b){this.clearCloseTimeout();(this.socket.connected||this.socket.connecting||this.socket.reconnecting)&&this.setCloseTimeout();if(""!==b&&(b=a.parser.decodePayload(b))&&b.length)for(var d=0,f=b.length;d<f;d++)this.onPacket(b[d]);return this};b.prototype.onPacket=function(a){this.socket.setHeartbeatTimeout();if("heartbeat"==a.type)return this.onHeartbeat();if("connect"==
a.type&&""==a.endpoint)this.onConnect();"error"==a.type&&"reconnect"==a.advice&&(this.open=!1);this.socket.onPacket(a);return this};b.prototype.setCloseTimeout=function(){if(!this.closeTimeout){var a=this;this.closeTimeout=setTimeout(function(){a.onDisconnect()},this.socket.closeTimeout)}};b.prototype.onDisconnect=function(){this.close&&this.open&&this.close();this.clearTimeouts();this.socket.onDisconnect();return this};b.prototype.onConnect=function(){this.socket.onConnect();return this};b.prototype.clearCloseTimeout=
function(){this.closeTimeout&&(clearTimeout(this.closeTimeout),this.closeTimeout=null)};b.prototype.clearTimeouts=function(){this.clearCloseTimeout();this.reopenTimeout&&clearTimeout(this.reopenTimeout)};b.prototype.packet=function(b){this.send(a.parser.encodePacket(b))};b.prototype.onHeartbeat=function(){this.packet({type:"heartbeat"})};b.prototype.onOpen=function(){this.open=!0;this.clearCloseTimeout();this.socket.onOpen()};b.prototype.onClose=function(){this.open=!1;this.socket.onClose();this.onDisconnect()};
b.prototype.prepareUrl=function(){var b=this.socket.options;return this.scheme()+"://"+b.host+":"+b.port+"/"+b.resource+"/"+a.protocol+"/"+this.name+"/"+this.sessid};b.prototype.ready=function(a,b){b.call(this)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(d,a,b){function c(c){this.options={port:80,secure:!1,document:"document"in b?document:!1,resource:"socket.io",transports:a.transports,"connect timeout":1E4,"try multiple transports":!0,reconnect:!0,"reconnection delay":500,"reconnection limit":Infinity,"reopen delay":3E3,"max reconnection attempts":10,"sync disconnect on unload":!0,"auto connect":!0,"flash policy port":10843};a.util.merge(this.options,c);this.reconnecting=this.connecting=this.open=this.connected=!1;this.namespaces={};this.buffer=
[];this.doBuffer=!1;if(this.options["sync disconnect on unload"]&&(!this.isXDomain()||a.util.ua.hasCORS)){var d=this;a.util.on(b,"unload",function(){d.disconnectSync()},!1)}this.options["auto connect"]&&this.connect()}function e(){}d.Socket=c;a.util.mixin(c,a.EventEmitter);c.prototype.of=function(b){this.namespaces[b]||(this.namespaces[b]=new a.SocketNamespace(this,b),""!==b&&this.namespaces[b].packet({type:"connect"}));return this.namespaces[b]};c.prototype.publish=function(){this.emit.apply(this,
arguments);var a,b;for(b in this.namespaces)this.namespaces.hasOwnProperty(b)&&(a=this.of(b),a.$emit.apply(a,arguments))};c.prototype.handshake=function(b){function c(a){if(a instanceof Error)d.onError(a.message);else b.apply(null,a.split(":"))}var d=this,g=this.options,g=["http"+(g.secure?"s":"")+":/",g.host+":"+g.port,g.resource,a.protocol,a.util.query(this.options.query,"t="+ +new Date)].join("/");if(this.isXDomain()&&!a.util.ua.hasCORS){var k=document.getElementsByTagName("script")[0],n=document.createElement("script");
n.src=g+"&jsonp="+a.j.length;k.parentNode.insertBefore(n,k);a.j.push(function(a){c(a);n.parentNode.removeChild(n)})}else{var l=a.util.request();l.open("GET",g,!0);l.withCredentials=!0;l.onreadystatechange=function(){4==l.readyState&&(l.onreadystatechange=e,200==l.status?c(l.responseText):!d.reconnecting&&d.onError(l.responseText))};l.send(null)}};c.prototype.getTransport=function(b){for(var b=b||this.transports,c=0,d;d=b[c];c++)if(a.Transport[d]&&a.Transport[d].check(this)&&(!this.isXDomain()||a.Transport[d].xdomainCheck()))return new a.Transport[d](this,
this.sessionid);return null};c.prototype.connect=function(b){if(this.connecting)return this;var c=this;this.handshake(function(d,g,e,n){function l(a){c.transport&&c.transport.clearTimeouts();c.transport=c.getTransport(a);if(!c.transport)return c.publish("connect_failed");c.transport.ready(c,function(){c.connecting=!0;c.publish("connecting",c.transport.name);c.transport.open();c.options["connect timeout"]&&(c.connectTimeoutTimer=setTimeout(function(){if(!c.connected&&(c.connecting=!1,c.options["try multiple transports"])){c.remainingTransports||
(c.remainingTransports=c.transports.slice(0));for(var a=c.remainingTransports;0<a.length&&a.splice(0,1)[0]!=c.transport.name;);a.length?l(a):c.publish("connect_failed")}},c.options["connect timeout"]))})}c.sessionid=d;c.closeTimeout=1E3*e;c.heartbeatTimeout=1E3*g;c.transports=n?a.util.intersect(n.split(","),c.options.transports):c.options.transports;c.setHeartbeatTimeout();l(c.transports);c.once("connect",function(){clearTimeout(c.connectTimeoutTimer);b&&"function"==typeof b&&b()})});return this};
c.prototype.setHeartbeatTimeout=function(){clearTimeout(this.heartbeatTimeoutTimer);var a=this;this.heartbeatTimeoutTimer=setTimeout(function(){a.transport.onClose()},this.heartbeatTimeout)};c.prototype.packet=function(a){this.connected&&!this.doBuffer?this.transport.packet(a):this.buffer.push(a);return this};c.prototype.setBuffer=function(a){this.doBuffer=a;!a&&this.connected&&this.buffer.length&&(this.transport.payload(this.buffer),this.buffer=[])};c.prototype.disconnect=function(){if(this.connected||
this.connecting)this.open&&this.of("").packet({type:"disconnect"}),this.onDisconnect("booted");return this};c.prototype.disconnectSync=function(){a.util.request().open("GET",this.resource+"/"+a.protocol+"/"+this.sessionid,!0);this.onDisconnect("booted")};c.prototype.isXDomain=function(){var a=b.location.port||("https:"==b.location.protocol?443:80);return this.options.host!==b.location.hostname||this.options.port!=a};c.prototype.onConnect=function(){this.connected||(this.connected=!0,this.connecting=
!1,this.doBuffer||this.setBuffer(!1),this.emit("connect"))};c.prototype.onOpen=function(){this.open=!0};c.prototype.onClose=function(){this.open=!1;clearTimeout(this.heartbeatTimeoutTimer)};c.prototype.onPacket=function(a){this.of(a.endpoint).onPacket(a)};c.prototype.onError=function(a){if(a&&a.advice&&"reconnect"===a.advice&&(this.connected||this.connecting))this.disconnect(),this.options.reconnect&&this.reconnect();this.publish("error",a&&a.reason?a.reason:a)};c.prototype.onDisconnect=function(a){var b=
this.connected,c=this.connecting;this.open=this.connecting=this.connected=!1;if(b||c)this.transport.close(),this.transport.clearTimeouts(),b&&(this.publish("disconnect",a),"booted"!=a&&this.options.reconnect&&!this.reconnecting&&this.reconnect())};c.prototype.reconnect=function(){function a(){if(c.connected){for(var d in c.namespaces)c.namespaces.hasOwnProperty(d)&&""!==d&&c.namespaces[d].packet({type:"connect"});c.publish("reconnect",c.transport.name,c.reconnectionAttempts)}clearTimeout(c.reconnectionTimer);
c.removeListener("connect_failed",b);c.removeListener("connect",b);c.reconnecting=!1;delete c.reconnectionAttempts;delete c.reconnectionDelay;delete c.reconnectionTimer;delete c.redoTransports;c.options["try multiple transports"]=e}function b(){if(c.reconnecting){if(c.connected)return a();if(c.connecting&&c.reconnecting)return c.reconnectionTimer=setTimeout(b,1E3);c.reconnectionAttempts++>=d?c.redoTransports?(c.publish("reconnect_failed"),a()):(c.on("connect_failed",b),c.options["try multiple transports"]=
!0,c.transport=c.getTransport(),c.redoTransports=!0,c.connect()):(c.reconnectionDelay<n&&(c.reconnectionDelay*=2),c.connect(),c.publish("reconnecting",c.reconnectionDelay,c.reconnectionAttempts),c.reconnectionTimer=setTimeout(b,c.reconnectionDelay))}}this.reconnecting=!0;this.reconnectionAttempts=0;this.reconnectionDelay=this.options["reconnection delay"];var c=this,d=this.options["max reconnection attempts"],e=this.options["try multiple transports"],n=this.options["reconnection limit"];this.options["try multiple transports"]=
!1;this.reconnectionTimer=setTimeout(b,this.reconnectionDelay);this.on("connect",b)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(d,a){function b(a,b){this.socket=a;this.name=b||"";this.flags={};this.json=new c(this,"json");this.ackPackets=0;this.acks={}}function c(a,b){this.namespace=a;this.name=b}d.SocketNamespace=b;a.util.mixin(b,a.EventEmitter);b.prototype.$emit=a.EventEmitter.prototype.emit;b.prototype.of=function(){return this.socket.of.apply(this.socket,arguments)};b.prototype.packet=function(a){a.endpoint=this.name;this.socket.packet(a);this.flags={};return this};b.prototype.send=function(a,b){var c={type:this.flags.json?
"json":"message",data:a};"function"==typeof b&&(c.id=++this.ackPackets,c.ack=!0,this.acks[c.id]=b);return this.packet(c)};b.prototype.emit=function(a){var b=Array.prototype.slice.call(arguments,1),c=b[b.length-1],d={type:"event",name:a};"function"==typeof c&&(d.id=++this.ackPackets,d.ack="data",this.acks[d.id]=c,b=b.slice(0,b.length-1));d.args=b;return this.packet(d)};b.prototype.disconnect=function(){""===this.name?this.socket.disconnect():(this.packet({type:"disconnect"}),this.$emit("disconnect"));
return this};b.prototype.onPacket=function(b){function c(){d.packet({type:"ack",args:a.util.toArray(arguments),ackId:b.id})}var d=this;switch(b.type){case "connect":this.$emit("connect");break;case "disconnect":if(""===this.name)this.socket.onDisconnect(b.reason||"booted");else this.$emit("disconnect",b.reason);break;case "message":case "json":var h=["message",b.data];"data"==b.ack?h.push(c):b.ack&&this.packet({type:"ack",ackId:b.id});this.$emit.apply(this,h);break;case "event":h=[b.name].concat(b.args);
"data"==b.ack&&h.push(c);this.$emit.apply(this,h);break;case "ack":this.acks[b.ackId]&&(this.acks[b.ackId].apply(this,b.args),delete this.acks[b.ackId]);break;case "error":if(b.advice)this.socket.onError(b);else"unauthorized"==b.reason?this.$emit("connect_failed",b.reason):this.$emit("error",b.reason)}};c.prototype.send=function(){this.namespace.flags[this.name]=!0;this.namespace.send.apply(this.namespace,arguments)};c.prototype.emit=function(){this.namespace.flags[this.name]=!0;this.namespace.emit.apply(this.namespace,
arguments)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(d,a,b){function c(b){a.Transport.apply(this,arguments)}d.websocket=c;a.util.inherit(c,a.Transport);c.prototype.name="websocket";c.prototype.open=function(){var c=a.util.query(this.socket.options.query),d=this,i;i||(i=b.MozWebSocket||b.WebSocket);this.websocket=new i(this.prepareUrl()+c);this.websocket.onopen=function(){d.onOpen();d.socket.setBuffer(!1)};this.websocket.onmessage=function(a){d.onData(a.data)};this.websocket.onclose=function(){d.onClose();d.socket.setBuffer(!0)};this.websocket.onerror=
function(a){d.onError(a)};return this};c.prototype.send=function(a){this.websocket.send(a);return this};c.prototype.payload=function(a){for(var b=0,c=a.length;b<c;b++)this.packet(a[b]);return this};c.prototype.close=function(){this.websocket.close();return this};c.prototype.onError=function(a){this.socket.onError(a)};c.prototype.scheme=function(){return this.socket.options.secure?"wss":"ws"};c.check=function(){return"WebSocket"in b&&!("__addTask"in WebSocket)||"MozWebSocket"in b};c.xdomainCheck=function(){return!0};
a.transports.push("websocket")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(d,a){function b(){a.Transport.websocket.apply(this,arguments)}d.flashsocket=b;a.util.inherit(b,a.Transport.websocket);b.prototype.name="flashsocket";b.prototype.open=function(){var b=this,d=arguments;WebSocket.__addTask(function(){a.Transport.websocket.prototype.open.apply(b,d)});return this};b.prototype.send=function(){var b=this,d=arguments;WebSocket.__addTask(function(){a.Transport.websocket.prototype.send.apply(b,d)});return this};b.prototype.close=function(){WebSocket.__tasks.length=
0;a.Transport.websocket.prototype.close.call(this);return this};b.prototype.ready=function(c,d){function f(){var a=c.options,g=a["flash policy port"],f=["http"+(a.secure?"s":"")+":/",a.host+":"+a.port,a.resource,"static/flashsocket","WebSocketMain"+(c.isXDomain()?"Insecure":"")+".swf"];b.loaded||("undefined"===typeof WEB_SOCKET_SWF_LOCATION&&(WEB_SOCKET_SWF_LOCATION=f.join("/")),843!==g&&WebSocket.loadFlashPolicyFile("xmlsocket://"+a.host+":"+g),WebSocket.__initialize(),b.loaded=!0);d.call(i)}var i=
this;if(document.body)return f();a.util.load(f)};b.check=function(){return"undefined"==typeof WebSocket||!("__initialize"in WebSocket)||!swfobject?!1:10<=swfobject.getFlashPlayerVersion().major};b.xdomainCheck=function(){return!0};"undefined"!=typeof window&&(WEB_SOCKET_DISABLE_AUTO_INITIALIZATION=!0);a.transports.push("flashsocket")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports);
if("undefined"!=typeof window)var swfobject=function(){function d(){if(!A){try{var a=m.getElementsByTagName("body")[0].appendChild(m.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}A=!0;for(var a=D.length,c=0;c<a;c++)D[c]()}}function a(a){A?a():D[D.length]=a}function b(a){if(typeof v.addEventListener!=o)v.addEventListener("load",a,!1);else if(typeof m.addEventListener!=o)m.addEventListener("load",a,!1);else if(typeof v.attachEvent!=o)q(v,"onload",a);else if("function"==typeof v.onload){var b=
v.onload;v.onload=function(){b();a()}}else v.onload=a}function c(){var a=m.getElementsByTagName("body")[0],b=m.createElement(s);b.setAttribute("type",p);var c=a.appendChild(b);if(c){var d=0;(function(){if(typeof c.GetVariable!=o){var g=c.GetVariable("$version");g&&(g=g.split(" ")[1].split(","),j.pv=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],10)])}else if(10>d){d++;setTimeout(arguments.callee,10);return}a.removeChild(b);c=null;e()})()}else e()}function e(){var a=y.length;if(0<a)for(var b=0;b<
a;b++){var c=y[b].id,d=y[b].callbackFn,e={success:!1,id:c};if(0<j.pv[0]){var k=r(c);if(k)if(t(y[b].swfVersion)&&!(j.wk&&312>j.wk))x(c,!0),d&&(e.success=!0,e.ref=f(c),d(e));else if(y[b].expressInstall&&i()){e={};e.data=y[b].expressInstall;e.width=k.getAttribute("width")||"0";e.height=k.getAttribute("height")||"0";k.getAttribute("class")&&(e.styleclass=k.getAttribute("class"));k.getAttribute("align")&&(e.align=k.getAttribute("align"));for(var n={},k=k.getElementsByTagName("param"),q=k.length,l=0;l<
q;l++)"movie"!=k[l].getAttribute("name").toLowerCase()&&(n[k[l].getAttribute("name")]=k[l].getAttribute("value"));h(e,n,c,d)}else g(k),d&&d(e)}else if(x(c,!0),d){if((c=f(c))&&typeof c.SetVariable!=o)e.success=!0,e.ref=c;d(e)}}}function f(a){var b=null;if((a=r(a))&&"OBJECT"==a.nodeName)typeof a.SetVariable!=o?b=a:(a=a.getElementsByTagName(s)[0])&&(b=a);return b}function i(){return!E&&t("6.0.65")&&(j.win||j.mac)&&!(j.wk&&312>j.wk)}function h(a,b,c,d){E=!0;H=d||null;K={success:!1,id:c};var g=r(c);if(g){"OBJECT"==
g.nodeName?(C=k(g),F=null):(C=g,F=c);a.id=L;if(typeof a.width==o||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if(typeof a.height==o||!/%$/.test(a.height)&&137>parseInt(a.height,10))a.height="137";m.title=m.title.slice(0,47)+" - Flash Player Installation";d=j.ie&&j.win?["Active"].concat("").join("X"):"PlugIn";d="MMredirectURL="+v.location.toString().replace(/&/g,"%26")+"&MMplayerType="+d+"&MMdoctitle="+m.title;b.flashvars=typeof b.flashvars!=o?b.flashvars+("&"+d):d;j.ie&&j.win&&4!=
g.readyState&&(d=m.createElement("div"),c+="SWFObjectNew",d.setAttribute("id",c),g.parentNode.insertBefore(d,g),g.style.display="none",function(){g.readyState==4?g.parentNode.removeChild(g):setTimeout(arguments.callee,10)}());n(a,b,c)}}function g(a){if(j.ie&&j.win&&4!=a.readyState){var b=m.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(k(a),b);a.style.display="none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(k(a),
a)}function k(a){var b=m.createElement("div");if(j.win&&j.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(s)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)!(1==a[d].nodeType&&"PARAM"==a[d].nodeName)&&8!=a[d].nodeType&&b.appendChild(a[d].cloneNode(!0));return b}function n(a,b,c){var d,g=r(c);if(j.wk&&312>j.wk)return d;if(g)if(typeof a.id==o&&(a.id=c),j.ie&&j.win){var e="",f;for(f in a)a[f]!=Object.prototype[f]&&("data"==f.toLowerCase()?b.movie=a[f]:"styleclass"==f.toLowerCase()?e+=
' class="'+a[f]+'"':"classid"!=f.toLowerCase()&&(e+=" "+f+'="'+a[f]+'"'));f="";for(var k in b)b[k]!=Object.prototype[k]&&(f+='<param name="'+k+'" value="'+b[k]+'" />');g.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+e+">"+f+"</object>";G[G.length]=a.id;d=r(a.id)}else{k=m.createElement(s);k.setAttribute("type",p);for(var h in a)a[h]!=Object.prototype[h]&&("styleclass"==h.toLowerCase()?k.setAttribute("class",a[h]):"classid"!=h.toLowerCase()&&k.setAttribute(h,a[h]));for(e in b)b[e]!=
Object.prototype[e]&&"movie"!=e.toLowerCase()&&(a=k,f=e,h=b[e],c=m.createElement("param"),c.setAttribute("name",f),c.setAttribute("value",h),a.appendChild(c));g.parentNode.replaceChild(k,g);d=k}return d}function l(a){var b=r(a);b&&"OBJECT"==b.nodeName&&(j.ie&&j.win?(b.style.display="none",function(){if(4==b.readyState){var c=r(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function r(a){var b=
null;try{b=m.getElementById(a)}catch(c){}return b}function q(a,b,c){a.attachEvent(b,c);B[B.length]=[a,b,c]}function t(a){var b=j.pv,a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function u(a,b,c,d){if(!j.ie||!j.mac){var g=m.getElementsByTagName("head")[0];if(g){c=c&&"string"==typeof c?c:"screen";d&&(I=w=null);if(!w||I!=c)d=m.createElement("style"),d.setAttribute("type","text/css"),
d.setAttribute("media",c),w=g.appendChild(d),j.ie&&j.win&&typeof m.styleSheets!=o&&0<m.styleSheets.length&&(w=m.styleSheets[m.styleSheets.length-1]),I=c;j.ie&&j.win?w&&typeof w.addRule==s&&w.addRule(a,b):w&&typeof m.createTextNode!=o&&w.appendChild(m.createTextNode(a+" {"+b+"}"))}}}function x(a,b){if(M){var c=b?"visible":"hidden";A&&r(a)?r(a).style.visibility=c:u("#"+a,"visibility:"+c)}}function J(a){return null!=/[\\\"<>\.;]/.exec(a)&&typeof encodeURIComponent!=o?encodeURIComponent(a):a}var o="undefined",
s="object",p="application/x-shockwave-flash",L="SWFObjectExprInst",v=window,m=document,z=navigator,N=!1,D=[function(){N?c():e()}],y=[],G=[],B=[],C,F,H,K,A=!1,E=!1,w,I,M=!0,j=function(){var a=typeof m.getElementById!=o&&typeof m.getElementsByTagName!=o&&typeof m.createElement!=o,b=z.userAgent.toLowerCase(),c=z.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,g=!+"\v1",e=[0,0,0],f=null;
if(typeof z.plugins!=o&&typeof z.plugins["Shockwave Flash"]==s){if((f=z.plugins["Shockwave Flash"].description)&&!(typeof z.mimeTypes!=o&&z.mimeTypes[p]&&!z.mimeTypes[p].enabledPlugin))N=!0,g=!1,f=f.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),e[0]=parseInt(f.replace(/^(.*)\..*$/,"$1"),10),e[1]=parseInt(f.replace(/^.*\.(.*)\s.*$/,"$1"),10),e[2]=/[a-zA-Z]/.test(f)?parseInt(f.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof v[["Active"].concat("Object").join("X")]!=o)try{var k=new (window[["Active"].concat("Object").join("X")])("ShockwaveFlash.ShockwaveFlash");
if(k&&(f=k.GetVariable("$version")))g=!0,f=f.split(" ")[1].split(","),e=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)]}catch(h){}return{w3:a,pv:e,wk:b,ie:g,win:d,mac:c}}();(function(){j.w3&&((typeof m.readyState!=o&&"complete"==m.readyState||typeof m.readyState==o&&(m.getElementsByTagName("body")[0]||m.body))&&d(),A||(typeof m.addEventListener!=o&&m.addEventListener("DOMContentLoaded",d,!1),j.ie&&j.win&&(m.attachEvent("onreadystatechange",function(){"complete"==m.readyState&&(m.detachEvent("onreadystatechange",
arguments.callee),d())}),v==top&&function(){if(!A){try{m.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}d()}}()),j.wk&&function(){A||(/loaded|complete/.test(m.readyState)?d():setTimeout(arguments.callee,0))}(),b(d)))})();(function(){j.ie&&j.win&&window.attachEvent("onunload",function(){for(var a=B.length,b=0;b<a;b++)B[b][0].detachEvent(B[b][1],B[b][2]);a=G.length;for(b=0;b<a;b++)l(G[b]);for(var c in j)j[c]=null;j=null;for(var d in swfobject)swfobject[d]=null;swfobject=
null})})();return{registerObject:function(a,b,c,d){if(j.w3&&a&&b){var g={};g.id=a;g.swfVersion=b;g.expressInstall=c;g.callbackFn=d;y[y.length]=g;x(a,!1)}else d&&d({success:!1,id:a})},getObjectById:function(a){if(j.w3)return f(a)},embedSWF:function(b,c,d,g,f,e,k,q,l,r){var m={success:!1,id:c};j.w3&&!(j.wk&&312>j.wk)&&b&&c&&d&&g&&f?(x(c,!1),a(function(){d+="";g+="";var a={};if(l&&typeof l===s)for(var j in l)a[j]=l[j];a.data=b;a.width=d;a.height=g;j={};if(q&&typeof q===s)for(var p in q)j[p]=q[p];if(k&&
typeof k===s)for(var u in k)j.flashvars=typeof j.flashvars!=o?j.flashvars+("&"+u+"="+k[u]):u+"="+k[u];if(t(f))p=n(a,j,c),a.id==c&&x(c,!0),m.success=!0,m.ref=p;else{if(e&&i()){a.data=e;h(a,j,c,r);return}x(c,!0)}r&&r(m)})):r&&r(m)},switchOffAutoHideShow:function(){M=!1},ua:j,getFlashPlayerVersion:function(){return{major:j.pv[0],minor:j.pv[1],release:j.pv[2]}},hasFlashPlayerVersion:t,createSWF:function(a,b,c){if(j.w3)return n(a,b,c)},showExpressInstall:function(a,b,c,d){j.w3&&i()&&h(a,b,c,d)},removeSWF:function(a){j.w3&&
l(a)},createCSS:function(a,b,c,d){j.w3&&u(a,b,c,d)},addDomLoadEvent:a,addLoadEvent:b,getQueryParamValue:function(a){var b=m.location.search||m.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return J(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return J(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(E){var a=r(L);a&&C&&(a.parentNode.replaceChild(C,a),F&&(x(F,!0),j.ie&&j.win&&(C.style.display="block")),
H&&H(K));E=!1}}}}();
(function(){if(!("undefined"==typeof window||window.WebSocket)){var d=window.console;if(!d||!d.log||!d.error)d={log:function(){},error:function(){}};swfobject.hasFlashPlayerVersion("10.0.0")?("file:"==location.protocol&&d.error("WARNING: web-socket-js doesn't work in file:///... URL unless you set Flash Security Settings properly. Open the page via Web server i.e. http://..."),WebSocket=function(a,b,c,d,f){var i=this;i.__id=WebSocket.__nextId++;WebSocket.__instances[i.__id]=i;i.readyState=WebSocket.CONNECTING;
i.bufferedAmount=0;i.__events={};b?"string"==typeof b&&(b=[b]):b=[];setTimeout(function(){WebSocket.__addTask(function(){WebSocket.__flash.create(i.__id,a,b,c||null,d||0,f||null)})},0)},WebSocket.prototype.send=function(a){if(this.readyState==WebSocket.CONNECTING)throw"INVALID_STATE_ERR: Web Socket connection has not been established";a=WebSocket.__flash.send(this.__id,encodeURIComponent(a));if(0>a)return!0;this.bufferedAmount+=a;return!1},WebSocket.prototype.close=function(){this.readyState==WebSocket.CLOSED||
this.readyState==WebSocket.CLOSING||(this.readyState=WebSocket.CLOSING,WebSocket.__flash.close(this.__id))},WebSocket.prototype.addEventListener=function(a,b){a in this.__events||(this.__events[a]=[]);this.__events[a].push(b)},WebSocket.prototype.removeEventListener=function(a,b){if(a in this.__events)for(var c=this.__events[a],d=c.length-1;0<=d;--d)if(c[d]===b){c.splice(d,1);break}},WebSocket.prototype.dispatchEvent=function(a){for(var b=this.__events[a.type]||[],c=0;c<b.length;++c)b[c](a);(b=this["on"+
a.type])&&b(a)},WebSocket.prototype.__handleEvent=function(a){"readyState"in a&&(this.readyState=a.readyState);"protocol"in a&&(this.protocol=a.protocol);if("open"==a.type||"error"==a.type)a=this.__createSimpleEvent(a.type);else if("close"==a.type)a=this.__createSimpleEvent("close");else if("message"==a.type)a=this.__createMessageEvent("message",decodeURIComponent(a.message));else throw"unknown event type: "+a.type;this.dispatchEvent(a)},WebSocket.prototype.__createSimpleEvent=function(a){if(document.createEvent&&
window.Event){var b=document.createEvent("Event");b.initEvent(a,!1,!1);return b}return{type:a,bubbles:!1,cancelable:!1}},WebSocket.prototype.__createMessageEvent=function(a,b){if(document.createEvent&&window.MessageEvent&&!window.opera){var c=document.createEvent("MessageEvent");c.initMessageEvent("message",!1,!1,b,null,null,window,null);return c}return{type:a,data:b,bubbles:!1,cancelable:!1}},WebSocket.CONNECTING=0,WebSocket.OPEN=1,WebSocket.CLOSING=2,WebSocket.CLOSED=3,WebSocket.__flash=null,WebSocket.__instances=
{},WebSocket.__tasks=[],WebSocket.__nextId=0,WebSocket.loadFlashPolicyFile=function(a){WebSocket.__addTask(function(){WebSocket.__flash.loadManualPolicyFile(a)})},WebSocket.__initialize=function(){if(!WebSocket.__flash)if(WebSocket.__swfLocation&&(window.WEB_SOCKET_SWF_LOCATION=WebSocket.__swfLocation),window.WEB_SOCKET_SWF_LOCATION){var a=document.createElement("div");a.id="webSocketContainer";a.style.position="absolute";WebSocket.__isFlashLite()?(a.style.left="0px",a.style.top="0px"):(a.style.left=
"-100px",a.style.top="-100px");var b=document.createElement("div");b.id="webSocketFlash";a.appendChild(b);document.body.appendChild(a);swfobject.embedSWF(WEB_SOCKET_SWF_LOCATION,"webSocketFlash","1","1","10.0.0",null,null,{hasPriority:!0,swliveconnect:!0,allowScriptAccess:"always"},null,function(a){a.success||d.error("[WebSocket] swfobject.embedSWF failed")})}else d.error("[WebSocket] set WEB_SOCKET_SWF_LOCATION to location of WebSocketMain.swf")},WebSocket.__onFlashInitialized=function(){setTimeout(function(){WebSocket.__flash=
document.getElementById("webSocketFlash");WebSocket.__flash.setCallerUrl(location.href);WebSocket.__flash.setDebug(!!window.WEB_SOCKET_DEBUG);for(var a=0;a<WebSocket.__tasks.length;++a)WebSocket.__tasks[a]();WebSocket.__tasks=[]},0)},WebSocket.__onFlashEvent=function(){setTimeout(function(){try{for(var a=WebSocket.__flash.receiveEvents(),b=0;b<a.length;++b)WebSocket.__instances[a[b].webSocketId].__handleEvent(a[b])}catch(c){d.error(c)}},0);return!0},WebSocket.__log=function(a){d.log(decodeURIComponent(a))},
WebSocket.__error=function(a){d.error(decodeURIComponent(a))},WebSocket.__addTask=function(a){WebSocket.__flash?a():WebSocket.__tasks.push(a)},WebSocket.__isFlashLite=function(){if(!window.navigator||!window.navigator.mimeTypes)return!1;var a=window.navigator.mimeTypes["application/x-shockwave-flash"];return!a||!a.enabledPlugin||!a.enabledPlugin.filename?!1:a.enabledPlugin.filename.match(/flashlite/i)?!0:!1},window.WEB_SOCKET_DISABLE_AUTO_INITIALIZATION||(window.addEventListener?window.addEventListener("load",
function(){WebSocket.__initialize()},!1):window.attachEvent("onload",function(){WebSocket.__initialize()}))):d.error("Flash Player >= 10.0.0 is required.")}})();
(function(d,a,b){function c(b){b&&(a.Transport.apply(this,arguments),this.sendBuffer=[])}function e(){}d.XHR=c;a.util.inherit(c,a.Transport);c.prototype.open=function(){this.socket.setBuffer(!1);this.onOpen();this.get();this.setCloseTimeout();return this};c.prototype.payload=function(b){for(var c=[],d=0,g=b.length;d<g;d++)c.push(a.parser.encodePacket(b[d]));this.send(a.parser.encodePayload(c))};c.prototype.send=function(a){this.post(a);return this};c.prototype.post=function(a){function c(){if(4==
this.readyState)if(this.onreadystatechange=e,g.posting=!1,200==this.status)g.socket.setBuffer(!1);else g.onClose()}function d(){this.onload=e;g.socket.setBuffer(!1)}var g=this;this.socket.setBuffer(!0);this.sendXHR=this.request("POST");b.XDomainRequest&&this.sendXHR instanceof XDomainRequest?this.sendXHR.onload=this.sendXHR.onerror=d:this.sendXHR.onreadystatechange=c;this.sendXHR.send(a)};c.prototype.close=function(){this.onClose();return this};c.prototype.request=function(b){var c=a.util.request(this.socket.isXDomain()),
d=a.util.query(this.socket.options.query,"t="+ +new Date);c.open(b||"GET",this.prepareUrl()+d,!0);if("POST"==b)try{c.setRequestHeader?c.setRequestHeader("Content-type","text/plain;charset=UTF-8"):c.contentType="text/plain"}catch(g){}return c};c.prototype.scheme=function(){return this.socket.options.secure?"https":"http"};c.check=function(c,d){try{var e=a.util.request(d),g=b.XDomainRequest&&e instanceof XDomainRequest,k=(c&&c.options&&c.options.secure?"https:":"http:")!=b.location.protocol;if(e&&(!g||
!k))return!0}catch(n){}return!1};c.xdomainCheck=function(){return c.check(null,!0)}})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(d,a){function b(b){a.Transport.XHR.apply(this,arguments)}d.htmlfile=b;a.util.inherit(b,a.Transport.XHR);b.prototype.name="htmlfile";b.prototype.get=function(){this.doc=new (window[["Active"].concat("Object").join("X")])("htmlfile");this.doc.open();this.doc.write("<html></html>");this.doc.close();this.doc.parentWindow.s=this;var b=this.doc.createElement("div");b.className="socketio";this.doc.body.appendChild(b);this.iframe=this.doc.createElement("iframe");b.appendChild(this.iframe);var d=
this,b=a.util.query(this.socket.options.query,"t="+ +new Date);this.iframe.src=this.prepareUrl()+b;a.util.on(window,"unload",function(){d.destroy()})};b.prototype._=function(a,b){this.onData(a);try{var d=b.getElementsByTagName("script")[0];d.parentNode.removeChild(d)}catch(i){}};b.prototype.destroy=function(){if(this.iframe){try{this.iframe.src="about:blank"}catch(a){}this.doc=null;this.iframe.parentNode.removeChild(this.iframe);this.iframe=null;CollectGarbage()}};b.prototype.close=function(){this.destroy();
return a.Transport.XHR.prototype.close.call(this)};b.check=function(){if("undefined"!=typeof window&&["Active"].concat("Object").join("X")in window)try{return new (window[["Active"].concat("Object").join("X")])("htmlfile")&&a.Transport.XHR.check()}catch(b){}return!1};b.xdomainCheck=function(){return!1};a.transports.push("htmlfile")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(d,a,b){function c(){a.Transport.XHR.apply(this,arguments)}function e(){}d["xhr-polling"]=c;a.util.inherit(c,a.Transport.XHR);a.util.merge(c,a.Transport.XHR);c.prototype.name="xhr-polling";c.prototype.open=function(){a.Transport.XHR.prototype.open.call(this);return!1};c.prototype.get=function(){function a(){if(4==this.readyState)if(this.onreadystatechange=e,200==this.status)g.onData(this.responseText),g.get();else g.onClose()}function c(){this.onerror=this.onload=e;g.onData(this.responseText);
g.get()}function d(){g.onClose()}if(this.open){var g=this;this.xhr=this.request();b.XDomainRequest&&this.xhr instanceof XDomainRequest?(this.xhr.onload=c,this.xhr.onerror=d):this.xhr.onreadystatechange=a;this.xhr.send(null)}};c.prototype.onClose=function(){a.Transport.XHR.prototype.onClose.call(this);if(this.xhr){this.xhr.onreadystatechange=this.xhr.onload=this.xhr.onerror=e;try{this.xhr.abort()}catch(b){}this.xhr=null}};c.prototype.ready=function(b,c){var d=this;a.util.defer(function(){c.call(d)})};
a.transports.push("xhr-polling")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(d,a,b){function c(b){a.Transport["xhr-polling"].apply(this,arguments);this.index=a.j.length;var c=this;a.j.push(function(a){c._(a)})}var e=b.document&&"MozAppearance"in b.document.documentElement.style;d["jsonp-polling"]=c;a.util.inherit(c,a.Transport["xhr-polling"]);c.prototype.name="jsonp-polling";c.prototype.post=function(b){function c(){d();g.socket.setBuffer(!1)}function d(){g.iframe&&g.form.removeChild(g.iframe);try{q=document.createElement('<iframe name="'+g.iframeId+'">')}catch(a){q=
document.createElement("iframe"),q.name=g.iframeId}q.id=g.iframeId;g.form.appendChild(q);g.iframe=q}var g=this,e=a.util.query(this.socket.options.query,"t="+ +new Date+"&i="+this.index);if(!this.form){var n=document.createElement("form"),l=document.createElement("textarea"),r=this.iframeId="socketio_iframe_"+this.index,q;n.className="socketio";n.style.position="absolute";n.style.top="0px";n.style.left="0px";n.style.display="none";n.target=r;n.method="POST";n.setAttribute("accept-charset","utf-8");
l.name="d";n.appendChild(l);document.body.appendChild(n);this.form=n;this.area=l}this.form.action=this.prepareUrl()+e;d();this.area.value=a.JSON.stringify(b);try{this.form.submit()}catch(t){}this.iframe.attachEvent?q.onreadystatechange=function(){"complete"==g.iframe.readyState&&c()}:this.iframe.onload=c;this.socket.setBuffer(!0)};c.prototype.get=function(){var b=this,c=document.createElement("script"),d=a.util.query(this.socket.options.query,"t="+ +new Date+"&i="+this.index);this.script&&(this.script.parentNode.removeChild(this.script),
this.script=null);c.async=!0;c.src=this.prepareUrl()+d;c.onerror=function(){b.onClose()};d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(c,d);this.script=c;e&&setTimeout(function(){var a=document.createElement("iframe");document.body.appendChild(a);document.body.removeChild(a)},100)};c.prototype._=function(a){this.onData(a);this.open&&this.get();return this};c.prototype.ready=function(b,c){var d=this;if(!e)return c.call(this);a.util.load(function(){c.call(d)})};c.check=function(){return"document"in
b};c.xdomainCheck=function(){return!0};a.transports.push("jsonp-polling")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);var Woogeen=Woogeen||{};
Woogeen.EventDispatcher=function(d){var a={};d.dispatcher={};d.dispatcher.eventListeners={};a.addEventListener=function(a,c){void 0===d.dispatcher.eventListeners[a]&&(d.dispatcher.eventListeners[a]=[]);d.dispatcher.eventListeners[a].push(c)};a.removeEventListener=function(a,c){if(d.dispatcher.eventListeners[a]){var e=d.dispatcher.eventListeners[a].indexOf(c);-1!==e&&d.dispatcher.eventListeners[a].splice(e,1)}};a.dispatchEvent=function(a){d.dispatcher.eventListeners[a.type]&&(Woogeen.Logger.debug("Event: "+
a.type),d.dispatcher.eventListeners[a.type].map(function(c){c(a)}))};return a};Woogeen.WoogeenEvent=function(d){var a={};a.type=d.type;return a};Woogeen.RoomEvent=function(d){var a=Woogeen.WoogeenEvent(d);a.streams=d.streams;return a};Woogeen.StreamEvent=function(d){var a=Woogeen.WoogeenEvent(d);a.stream=d.stream;a.msg=d.msg;return a};Woogeen.ClientEvent=function(d){var a=Woogeen.WoogeenEvent(d);a.user=d.user;a.attr=d.attr;return a};Woogeen=Woogeen||{};Woogeen.FcStack=function(){return{addStream:function(){}}};Woogeen=Woogeen||{};
Woogeen.ChromeJsepStack=function(d){var a={pc_config:{iceServers:[]},pc_constraints:{optional:[{DtlsSrtpKeyAgreement:!1}]}};void 0!==d.stunServerUrl&&(a.pc_config.iceServers=d.stunServerUrl);a.mediaConstraints={mandatory:{OfferToReceiveVideo:"true",OfferToReceiveAudio:"true"}};a.peerConnection=new webkitRTCPeerConnection(a.pc_config,a.pc_constraints);a.peerConnection.onicecandidate=function(b){Woogeen.Logger.debug("PeerConnection: ",d.session_id);if(b.candidate)a.iceCandidateCount=a.iceCandidateCount+
1;else{Woogeen.Logger.debug("State: "+a.peerConnection.iceGatheringState);if(a.ices===void 0)a.ices=0;a.ices=a.ices+1;Woogeen.Logger.debug(a.ices);if(a.ices>=1&&a.moreIceComing){a.moreIceComing=false;a.markActionNeeded()}}};Woogeen.Logger.info('Created webkitRTCPeerConnnection with config "'+JSON.stringify(a.pc_config)+'".');var b=function(a){if(d.maxVideoBW!==void 0){var b=a.match(/m=video.*\r\n/);if(b!==null)var f=b[0]+"b=AS:"+d.maxVideoBW+"\r\n",a=a.replace(b[0],f)}if(d.maxAudioBW!==void 0){b=
a.match(/m=audio.*\r\n/);if(b!==null){f=b[0]+"b=AS:"+d.maxAudioBW+"\r\n";a=a.replace(b[0],f)}}return a};a.processSignalingMessage=function(c){c=JSON.parse(c);if(a.state==="new")if(c.type==="offer"){a.peerConnection.setRemoteDescription(new RTCSessionDescription(c));a.state="offer-received";a.markActionNeeded()}else a.error("Illegal message for this state: "+c.messageType+" in state "+a.state);else if(a.state==="offer-sent")if(c.type==="answer"){Woogeen.Logger.trace("Received ANSWER: ",c);c.sdp=b(c.sdp);
a.peerConnection.setRemoteDescription(new RTCSessionDescription(c));a.sendOK();a.state="established"}else c.type==="pr-answer"?a.peerConnection.setRemoteDescription(new RTCSessionDescription(c)):c.type==="offer"?a.error("Not written yet"):a.error("Illegal message for this state: "+c.type+" in state "+a.state);else if(a.state==="established")if(c.type==="offer"){a.peerConnection.setRemoteDescription(new RTCSessionDescription(c));a.state="offer-received";a.markActionNeeded()}else a.error("Illegal message for this state: "+
c.messageType+" in state "+a.state)};a.addStream=function(b){try{a.peerConnection.addStream(b);a.markActionNeeded()}catch(d){Woogeen.Logger.error(d.message)}};a.removeStream=function(){a.markActionNeeded()};a.close=function(){if(a.state!=="closed"){a.state="closed";a.peerConnection.close()}};a.markActionNeeded=function(){a.actionNeeded=true;a.doLater(function(){a.onstablestate()})};a.doLater=function(a){window.setTimeout(a,1)};a.onstablestate=function(){var c;if(a.actionNeeded){if(a.state==="new"||
a.state==="established")a.peerConnection.createOffer(function(c){c.sdp=b(c.sdp);var d=c.sdp;Woogeen.Logger.debug("Changed",c.sdp);if(d!==a.prevOffer){a.peerConnection.setLocalDescription(c);a.state="preparing-offer";a.markActionNeeded()}else Woogeen.Logger.debug("Not sending a new offer")},null,a.mediaConstraints);else if(a.state==="preparing-offer"){if(a.moreIceComing)return;a.prevOffer=a.peerConnection.localDescription.sdp;Woogeen.Logger.trace("Sending OFFER: ",a.prevOffer);a.sendMessage({type:"offer",
sdp:a.prevOffer});a.state="offer-sent"}else if(a.state==="offer-received")a.peerConnection.createAnswer(function(b){a.peerConnection.setLocalDescription(b);a.state="offer-received-preparing-answer";if(a.iceStarted)a.markActionNeeded();else{Woogeen.Logger.debug((new Date).getTime()+": Starting ICE in responder");a.iceStarted=true}},null,a.mediaConstraints);else if(a.state==="offer-received-preparing-answer"){if(a.moreIceComing)return;c=a.peerConnection.localDescription.sdp;a.sendMessage({type:"answer",
sdp:c});a.state="established"}else a.error("Dazed and confused in state "+a.state+", stopping here");a.actionNeeded=false}};a.sendOK=function(){a.sendMessage("OK")};a.sendMessage=function(b){b=JSON.stringify(b);Woogeen.Logger.debug("C->S: "+b);a.onsignalingmessage(b)};a.error=function(a){throw"Error in RoapOnJsep: "+a;};a.sequenceNumber=0;a.actionNeeded=!1;a.iceStarted=!1;a.moreIceComing=!0;a.iceCandidateCount=0;a.onsignalingmessage=d.callback;a.peerConnection.onopen=function(){if(a.onopen)a.onopen()};
a.peerConnection.onaddstream=function(b){if(a.onaddstream)a.onaddstream(b)};a.peerConnection.onremovestream=function(b){if(a.onremovestream)a.onremovestream(b)};a.onaddstream=null;a.onremovestream=null;a.state="new";a.markActionNeeded();return a};Woogeen=Woogeen||{};Woogeen.sessionId=103;
Woogeen.Connection=function(d){var a={};d.session_id=Woogeen.sessionId+=1;a.browser="";if("undefined"!==typeof module&&module.exports)Woogeen.Logger.error("Publish/subscribe video/audio streams not supported in woogeenfc yet"),a=Woogeen.FcStack(d);else if(window.navigator.userAgent.match(/Firefox\/([0-9]+)/))22<=window.navigator.userAgent.match(/Firefox\/([0-9]+)/)[0].split("/")[1]&&Woogeen.Logger.debug("Firefox 22+"),a.browser="firefox";else if(24<=window.navigator.userAgent.match(/Chrome\/([0-9]+)/)[1])Woogeen.Logger.debug("Chrome 24+"),a=
Woogeen.ChromeJsepStack(d),a.browser="chrome";else if("25"===window.navigator.appVersion.match(/Bowser\/([\w\W]*?)\./)[1])a.browser="bowser";else throw a.browser="none","WebRTC stack not available";return a};
Woogeen.GetUserMedia=function(d,a,b){navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia;if(d.screen)Woogeen.Logger.debug("Screen access requested"),34<=window.navigator.appVersion.match(/Chrome\/([\w\W]*?)\./)[1]&&(Woogeen.Logger.debug("Screen access on chrome stable, looking for extension"),chrome.runtime.sendMessage(Woogeen.ClientConfig&&Woogeen.ClientConfig.screenSharingExtensionId?Woogeen.ClientConfig.screenSharingExtensionId:"pndohhifhheefbpeljcmnhnkphepimhe",
{getStream:!0},function(c){Woogeen.Logger.debug("The ID of the screen stream is ID");console.log(c);c=c.streamId;d=d.videoSize?{video:{mandatory:{chromeMediaSource:"desktop",chromeMediaSourceId:c,minWidth:d.videoSize[0],minHeight:d.videoSize[1],maxWidth:d.videoSize[2],maxHeight:d.videoSize[3]}}}:{video:{mandatory:{chromeMediaSource:"desktop",chromeMediaSourceId:c}}};navigator.getUserMedia(d,a,b)}));else if("undefined"!==typeof module&&module.exports)Woogeen.Logger.error("Video/audio streams not supported in woogeenfc yet");
else try{navigator.getUserMedia("audio, video",a,b),Woogeen.Logger.debug("GetUserMedia BOWSER")}catch(c){navigator.getUserMedia(d,a,b),Woogeen.Logger.debug("GetUserMedia CHROME",d)}};Woogeen=Woogeen||{};
Woogeen.Stream=function(d){function a(){d.video&&(b.stream.getVideoTracks()[0].enabled=!d.video_inactive);d.audio&&(b.stream.getAudioTracks()[0].enabled=!d.audio_inactive)}var b=Woogeen.EventDispatcher(d),c;b.stream=d.stream;b.onClose=void 0;b.showing=!1;b.local=!1;b.screen=d.screen;b.videoSize=d.videoSize;if(void 0===d.local||!0===d.local)b.local=!0;b.initialized=!b.local;b.getID=function(){return d.streamID};b.isMix=function(){return d.mix};b.getAttributes=function(a){return d.mix?void 0===a?d.attributes.self:
d.attributes[a]:d.attributes};b.hasAudio=function(){return d.audio};b.hasVideo=function(){return d.video};b.hasData=function(){return d.data};b.hasScreen=function(){return d.screen};b.sendData=function(){};b.isAudioInactive=function(){return d.audio&&!b.stream.getAudioTracks()[0].enabled};b.isVideoInactive=function(){return d.video&&!b.stream.getVideoTracks()[0].enabled};b.init=function(){if(!0===b.initialized)Woogeen.Logger.debug("Stream is already initialized");else if(!0!==b.local)Woogeen.Logger.debug("Stream is not local");
else try{if(d.audio||d.video||d.screen){Woogeen.Logger.debug("Requested access to local media");var c=d.video;Woogeen.Logger.debug("videoSize:"+JSON.stringify(b.videoSize));!0==c&&void 0!==b.videoSize&&(c={mandatory:{minWidth:b.videoSize[0],minHeight:b.videoSize[1],maxWidth:b.videoSize[2],maxHeight:b.videoSize[3]}});var f={video:c,audio:d.audio,screen:d.screen,videoSize:d.videoSize};Woogeen.Logger.debug("options for Getusermedia:"+JSON.stringify(f));Woogeen.GetUserMedia(f,function(c){Woogeen.Logger.info("User has granted access to local media.");
b.stream=c;d.screen&&d.audio?Woogeen.GetUserMedia({audio:!0},function(c){var d=c.getAudioTracks()[0];b.stream.getVideoTracks()[0].onended=function(){b.stream.removeTrack(b.stream.getAudioTracks()[0]);c.stop();b.close()};b.stream.addTrack(d);a();d=Woogeen.StreamEvent({type:"access-accepted"});b.dispatchEvent(d)},function(a){b.stream.stop();b.stream=void 0;Woogeen.Logger.error("Failed to get access to local audio:",a);b.dispatchEvent(Woogeen.StreamEvent({type:"access-denied"}))}):(a(),c=Woogeen.StreamEvent({type:"access-accepted"}),
b.dispatchEvent(c))},function(a){Woogeen.Logger.error("Failed to get access to local media:",a);a=Woogeen.StreamEvent({type:"access-denied"});b.dispatchEvent(a)})}else{var i=Woogeen.StreamEvent({type:"access-accepted"});b.dispatchEvent(i)}b.initialized=!0}catch(h){Woogeen.Logger.error("Error accessing to local media")}};b.close=function(){if(!0===b.initialized&&b.local){if("function"===typeof b.onClose)b.onClose();b.hide();void 0!==b.stream&&b.stream.stop();b.stream=void 0;b.initialized=!1}};b.show=
function(a,c){b.elementID=a;if((b.hasVideo()||b.hasAudio()||b.hasScreen())&&void 0!==a){var d=new Woogeen.VideoPlayer({id:b.getID(),stream:b,elementID:a,options:c});b.player=d;b.showing=!0}};b.hide=function(){b.showing&&void 0!==b.player&&(b.player.destroy(),b.showing=!1)};c=function(){if(void 0!==b.player&&void 0!==b.stream){var a=b.player.video,c=document.defaultView.getComputedStyle(a),d=parseInt(c.getPropertyValue("width"),10),h=parseInt(c.getPropertyValue("height"),10),g=parseInt(c.getPropertyValue("left"),
10),c=parseInt(c.getPropertyValue("top"),10),k=document.getElementById(b.elementID),n=document.defaultView.getComputedStyle(k),k=parseInt(n.getPropertyValue("width"),10),n=parseInt(n.getPropertyValue("height"),10),l=document.createElement("canvas");l.id="testing";l.width=k;l.height=n;l.setAttribute("style","display: none");l.getContext("2d").drawImage(a,g,c,d,h);return l}return null};b.getVideoFrameURL=function(){var a=c();return null!==a?a.toDataURL():null};b.getVideoFrame=function(){var a=c();return null!==
a?a.getContext("2d").getImageData(0,0,a.width,a.height):null};b.enableAudio=function(){return b.hasAudio()&&b.initialized&&!0!==b.stream.getAudioTracks()[0].enabled?b.stream.getAudioTracks()[0].enabled=!0:!1};b.disableAudio=function(){return b.hasAudio()&&b.initialized&&b.stream.getAudioTracks()[0].enabled?(b.stream.getAudioTracks()[0].enabled=!1,!0):!1};b.enableVideo=function(){return b.hasVideo()&&b.initialized&&!0!==b.stream.getVideoTracks()[0].enabled?b.stream.getVideoTracks()[0].enabled=!0:!1};
b.disableVideo=function(){return b.hasVideo()&&b.initialized&&b.stream.getVideoTracks()[0].enabled?(b.stream.getVideoTracks()[0].enabled=!1,!0):!1};b.playAudio=function(a,c){if(b.enableAudio()&&"function"===typeof b.signalOnPlayAudio)return b.signalOnPlayAudio(a,c);"function"===typeof c&&c("unable to call playAudio")};b.pauseAudio=function(a,c){if(b.disableAudio()&&"function"===typeof b.signalOnPauseAudio)return b.signalOnPauseAudio(a,c);"function"===typeof c&&c("unable to call pauseAudio")};b.playVideo=
function(a,c){if(b.enableVideo()&&"function"===typeof b.signalOnPlayVideo)return b.signalOnPlayVideo(a,c);"function"===typeof c&&c("unable to call playVideo")};b.pauseVideo=function(a,c){if(b.disableVideo()&&"function"===typeof b.signalOnPauseVideo)return b.signalOnPauseVideo(a,c);"function"===typeof c&&c("unable to call pauseVideo")};return b};Woogeen=Woogeen||{};
Woogeen.Room=function(d){function a(a,b){return{type:"control",payload:{action:a,streamId:b}}}var b=Woogeen.EventDispatcher(d),c,e,f,i,h;b.remoteStreams={};b.localStreams={};b.roomID="";b.socket={};b.state=0;b.addEventListener("room-disconnected",function(){var a,c;b.state=0;for(a in b.remoteStreams)b.remoteStreams.hasOwnProperty(a)&&(c=b.remoteStreams[a],h(c),delete b.remoteStreams[a],c=Woogeen.StreamEvent({type:"stream-removed",stream:c}),b.dispatchEvent(c));b.remoteStreams={};for(a in b.localStreams)b.localStreams.hasOwnProperty(a)&&
(c=b.localStreams[a],c.pc&&"function"===typeof c.pc.close&&(c.pc.close(),c.pc=void 0),delete b.localStreams[a]);try{b.socket.disconnect()}catch(d){Woogeen.Logger.debug("Socket already disconnected")}b.socket=void 0});h=function(a){void 0!==a.stream&&(a.hide(),a.pc.close(),a.local&&a.stream.stop())};i=function(a,b){a.local&&e("sendDataStream",{id:a.getID(),msg:b})};c=function(a,c,f){var l="https:"===window.location.protocol;void 0!==d.secure&&"boolean"===typeof d.secure&&(l=d.secure);var i;l?(i=a.host+
":"+a.sport,delete io.sockets["https://"+i]):(i=a.host+":"+a.port,delete io.sockets["http://"+i]);b.socket=io.connect(i,{reconnect:!1,secure:l});b.socket.on("onAddStream",function(a){Woogeen.Logger.debug(a);if(b.remoteStreams[a.id]===void 0){var c=Woogeen.Stream({mix:a.mix,streamID:a.id,local:false,audio:a.audio,video:a.video,screen:a.screen,data:a.data,attributes:a.attributes});b.remoteStreams[a.id]=c;a=Woogeen.StreamEvent({type:"stream-added",stream:c})}else{c=Woogeen.Stream({mix:a.mix,streamID:a.id,
local:false,audio:a.audio,video:a.video,screen:a.screen,data:a.data,attributes:a.attributes});a=Woogeen.StreamEvent({type:"stream-changed",stream:c})}b.dispatchEvent(a)});b.socket.on("onDataStream",function(a){var c=b.remoteStreams[a.id];if(c){a=Woogeen.StreamEvent({type:"stream-data",msg:a.msg,stream:c});c.dispatchEvent(a)}});b.socket.on("onRemoveStream",function(a){var c=b.remoteStreams[a.id];if(c){delete b.remoteStreams[a.id];h(c);a=Woogeen.StreamEvent({type:"stream-removed",stream:c});b.dispatchEvent(a)}});
b.socket.on("onChangeStream",function(a){if(a.mix===true)if(b.remoteStreams[a.id]!==void 0){a=Woogeen.Stream({mix:a.mix,streamID:a.id,local:false,audio:a.audio,video:a.video,screen:a.screen,data:a.data,attributes:a.attributes});a=Woogeen.StreamEvent({type:"stream-changed",stream:a});b.dispatchEvent(a)}else Woogeen.Logger.debug("Changes on a missing stream.")});b.socket.on("onClientJoin",function(a){a=Woogeen.ClientEvent({type:"client-joined",attr:a.attr,user:a.user});b.dispatchEvent(a)});b.socket.on("onClientLeave",
function(a){a=Woogeen.ClientEvent({type:"client-left",attr:a.attr,user:a.user});b.dispatchEvent(a)});b.socket.on("connect_failed",function(a){Woogeen.Logger.error("connect_failed",a);a=Woogeen.ClientEvent({type:"client-error",attr:"connect_failed"});b.dispatchEvent(a)});b.socket.on("connect_timeout",function(a){Woogeen.Logger.error("connect_timeout",a);a=Woogeen.ClientEvent({type:"client-error",attr:"connect_timeout"});b.dispatchEvent(a)});b.socket.on("error",function(a){Woogeen.Logger.error("connect_error",
a);a=Woogeen.ClientEvent({type:"client-error",attr:"connect_error"});b.dispatchEvent(a)});b.socket.on("disconnect",function(){Woogeen.Logger.info("Socket disconnected");if(b.state!==0){var a=Woogeen.RoomEvent({type:"room-disconnected"});b.dispatchEvent(a)}});e("token",a,c,f)};e=function(a,c,d,f){try{b.socket.emit(a,c,function(a,b){"success"===a?"function"===typeof d&&d(b):"function"===typeof f&&f(b)})}catch(e){Woogeen.Logger.error("Error in sendMessageSocket():",e)}};f=function(a,c,d,f){try{b.socket.emit(a,
c,d,function(a,b){"function"===typeof f&&f(a,b)})}catch(e){Woogeen.Logger.error("Error in sendSDPSocket():",e)}};b.send=function(a,b,c){e("customMessage",a,b,c)};b.connect=function(){var a=JSON.parse(Woogeen.Base64.decodeBase64(d.token));0!==b.state&&Woogeen.Logger.error("Room already connected");b.state=1;c(a,function(a){var c=0,g=[],f,e,h;f=a.streams;e=a.id;b.stunServerUrl=a.stunServerUrl;d.maxVideoBW=a.maxVideoBW;d.maxAudioBW=a.maxAudioBW;b.state=2;for(c in f)f.hasOwnProperty(c)&&(h=f[c],Woogeen.Logger.debug(h),
a=Woogeen.Stream({mix:h.mix,streamID:h.id,local:!1,audio:h.audio,video:h.video,screen:h.screen,data:h.data,attributes:h.attributes}),g.push(a),b.remoteStreams[h.id]=a);b.roomID=e;Woogeen.Logger.info("Connected to room "+b.roomID);c=Woogeen.RoomEvent({type:"room-connected",streams:g});b.dispatchEvent(c)},function(a){Woogeen.Logger.error("Not Connected! Error: "+a)})};b.disconnect=function(){var a=Woogeen.RoomEvent({type:"room-disconnected"});b.dispatchEvent(a)};b.publish=function(c,e){e=e||{};e.maxVideoBW>
d.maxVideoBW&&(e.maxVideoBW=d.maxVideoBW);e.maxAudioBW>d.maxAudioBW&&(e.maxAudioBW=d.maxAudioBW);"object"===typeof c&&null!==c?c.local&&void 0===b.localStreams[c.getID()]&&(c.hasAudio()||c.hasVideo()||c.hasScreen()?(c.pc=Woogeen.Connection({callback:function(d){var h={state:"offer",data:true,audio:c.hasAudio(),video:c.hasVideo(),screen:c.hasScreen(),attributes:c.getAttributes(),prefs:e.prefers};f("publish",h,d,function(d,e){if(d==="error")Woogeen.Logger.error("Stream publish failed:",e);else{c.pc.onsignalingmessage=
function(d){c.pc.onsignalingmessage=function(){};h.state="ok";h.streamId=e;c.isAudioInactive()&&(h.audio_inactive=true);c.isVideoInactive()&&(h.video_inactive=true);f("publish",h,d);Woogeen.Logger.info("Stream published");c.getID=function(){return e};c.sendData=function(a){i(c,a)};b.localStreams[e]=c;c.onClose=function(){b.unpublish(c)};c.signalOnPlayAudio=function(d,e){b.send(a("audio-out-on",c.getID()),d,e)};c.signalOnPauseAudio=function(d,e){b.send(a("audio-out-off",c.getID()),d,e)};c.signalOnPlayVideo=
function(d,e){b.send(a("video-out-on",c.getID()),d,e)};c.signalOnPauseVideo=function(d,e){b.send(a("video-out-off",c.getID()),d,e)}};c.pc.processSignalingMessage(d)}})},stunServerUrl:b.stunServerUrl,maxVideoBW:e.maxVideoBW,maxAudioBW:e.maxAudioBW}),c.pc.addStream(c.stream)):c.hasData()&&f("publish",{state:"data",data:!0,audio:!1,video:!1,screen:!1,attributes:c.getAttributes()},void 0,function(a,d){if(a==="error")Woogeen.Logger.error("Stream publish failed:",d);else{Woogeen.Logger.info("Stream published");
c.getID=function(){return d};c.sendData=function(a){i(c,a)};b.localStreams[d]=c;c.onClose=function(){b.unpublish(c)}}})):Woogeen.Logger.error("No stream to publish")};b.unpublish=function(a){a.local&&void 0!==b.localStreams[a.getID()]&&e("unpublish",a.getID(),function(c,d){if("error"===c)Woogeen.Logger.error("Stream unpublish failed:",d);else{if(a.hasAudio()||a.hasVideo()||a.hasScreen())a.pc.close(),a.pc=void 0;delete b.localStreams[a.getID()];a.getID=function(){};a.sendData=function(){};a.onClose=
void 0;a.signalOnPlayAudio=void 0;a.signalOnPauseAudio=void 0;a.signalOnPlayVideo=void 0;a.signalOnPauseVideo=void 0}})};b.subscribe=function(c,d){c.local||(c.hasVideo()||c.hasAudio()||c.hasScreen()?(c.pc=Woogeen.Connection({callback:function(a){f("subscribe",{streamId:c.getID(),prefs:d},a,function(a,b){"error"===a?Woogeen.Logger.error("Stream subscribe failed:",b):(Woogeen.Logger.info("Got answer to subscribe:"+c.getID()),c.pc.processSignalingMessage(a))})},stunServerUrl:b.stunServerUrl}),c.pc.onaddstream=
function(d){Woogeen.Logger.info("Stream subscribed");c.stream=d.stream;d=Woogeen.StreamEvent({type:"stream-subscribed",stream:c});b.dispatchEvent(d);c.signalOnPlayAudio=function(d,e){b.send(a("audio-in-on",c.getID()),d,e)};c.signalOnPauseAudio=function(d,e){b.send(a("audio-in-off",c.getID()),d,e)};c.signalOnPlayVideo=function(d,e){b.send(a("video-in-on",c.getID()),d,e)};c.signalOnPauseVideo=function(d,e){b.send(a("video-in-off",c.getID()),d,e)}}):c.hasData()&&f("subscribe",{streamId:c.getID()},void 0,
function(a,d){if("error"===a)Woogeen.Logger.error("Stream subscribe failed:",d);else{Woogeen.Logger.info("Stream subscribed");var e=Woogeen.StreamEvent({type:"stream-subscribed",stream:c});b.dispatchEvent(e)}}),Woogeen.Logger.info("Subscribing to: "+c.getID()))};b.unsubscribe=function(a){void 0!==b.socket&&(a.local||e("unsubscribe",a.getID(),function(b,c){"error"===b?Woogeen.Logger.error("Stream unsubscribe failed:",c):(a.signalOnPlayAudio=void 0,a.signalOnPauseAudio=void 0,a.signalOnPlayVideo=void 0,
a.signalOnPauseVideo=void 0,h(a))}))};b.getStreamsByAttribute=function(a,c){var d=[],e,f;for(e in b.remoteStreams)b.remoteStreams.hasOwnProperty(e)&&(f=b.remoteStreams[e],void 0!==f.getAttributes()&&void 0!==f.getAttributes()[a]&&f.getAttributes()[a]===c&&d.push(f));return d};return b};Woogeen=Woogeen||{};
Woogeen.Logger=function(d){var a;a=function(){var a=arguments[0],c=arguments;if(!(a<d.Logger.logLevel)){switch(a){case d.Logger.DEBUG:c[0]="DEBUG:";break;case d.Logger.TRACE:c[0]="TRACE:";break;case d.Logger.INFO:c[0]="INFO:";break;case d.Logger.WARNING:c[0]="WARNING:";break;case d.Logger.ERROR:c[0]="ERROR:";break;default:return}console.log.apply(console,c)}};return{DEBUG:0,TRACE:1,INFO:2,WARNING:3,ERROR:4,NONE:5,setLogLevel:function(a){a>d.Logger.NONE?a=d.Logger.NONE:a<d.Logger.DEBUG&&(a=d.Logger.DEBUG);
d.Logger.logLevel=a},log:a,debug:function(){for(var b=[d.Logger.DEBUG],c=0;c<arguments.length;c++)b.push(arguments[c]);a.apply(this,b)},trace:function(){for(var b=[d.Logger.TRACE],c=0;c<arguments.length;c++)b.push(arguments[c]);a.apply(this,b)},info:function(){for(var b=[d.Logger.INFO],c=0;c<arguments.length;c++)b.push(arguments[c]);a.apply(this,b)},warning:function(){for(var b=[d.Logger.WARNING],c=0;c<arguments.length;c++)b.push(arguments[c]);a.apply(this,b)},error:function(){for(var b=[d.Logger.ERROR],
c=0;c<arguments.length;c++)b.push(arguments[c]);a.apply(this,b)}}}(Woogeen);Woogeen=Woogeen||{};
Woogeen.Base64=function(){var d,a,b,c,e,f,i,h,g;d="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,+,/".split(",");a=[];for(e=0;e<d.length;e+=1)a[d[e]]=e;f=function(a){b=a;c=0};i=function(){var a;if(!b||c>=b.length)return-1;a=b.charCodeAt(c)&255;c+=1;return a};h=function(){if(!b)return-1;for(;;){if(c>=b.length)return-1;var d=b.charAt(c);c+=1;if(a[d])return a[d];if("A"===d)return 0}};g=function(a){a=a.toString(16);1===a.length&&
(a="0"+a);return unescape("%"+a)};return{encodeBase64:function(a){var b,c,e;f(a);a="";b=Array(3);c=0;for(e=!1;!e&&-1!==(b[0]=i());)if(b[1]=i(),b[2]=i(),a+=d[b[0]>>2],-1!==b[1]?(a+=d[b[0]<<4&48|b[1]>>4],-1!==b[2]?(a+=d[b[1]<<2&60|b[2]>>6],a+=d[b[2]&63]):(a+=d[b[1]<<2&60],a+="=",e=!0)):(a+=d[b[0]<<4&48],a+="=",a+="=",e=!0),c+=4,76<=c)a+="\n",c=0;return a},decodeBase64:function(a){var b,c;f(a);a="";b=Array(4);for(c=!1;!c&&-1!==(b[0]=h())&&-1!==(b[1]=h());)b[2]=h(),b[3]=h(),a+=g(b[0]<<2&255|b[1]>>4),
-1!==b[2]?(a+=g(b[1]<<4&255|b[2]>>2),-1!==b[3]?a+=g(b[2]<<6&255|b[3]):c=!0):c=!0;return a}}}(Woogeen);Woogeen=Woogeen||{};Woogeen.View=function(){var d=Woogeen.EventDispatcher({});d.url=".";return d};Woogeen=Woogeen||{};
Woogeen.VideoPlayer=function(d){var a=Woogeen.View({});a.id=d.id;a.stream=d.stream.stream;a.elementID=d.elementID;a.options=d.options;a.destroy=function(){a.video.pause();clearInterval(a.resize);a.parentNode.removeChild(a.div)};Woogeen.Logger.debug("Creating URL from stream "+a.stream);a.stream_url=webkitURL.createObjectURL(a.stream);a.div=document.createElement("div");a.div.setAttribute("id","player_"+a.id);a.div.setAttribute("style","width: 100%; height: 100%; position: relative; background-color: black; overflow: hidden;");a.loader=
document.createElement("img");a.loader.setAttribute("style","width: 16px; height: 16px; position: absolute; top: 50%; left: 50%; margin-top: -8px; margin-left: -8px");a.loader.setAttribute("id","back_"+a.id);a.loader.setAttribute("src",a.url+"/assets/loader.gif");a.video=document.createElement("video");a.video.setAttribute("id","stream"+a.id);a.video.setAttribute("style","width: 100%; height: 100%; position: absolute");a.video.setAttribute("autoplay","autoplay");void 0!==a.options&&void 0!==a.options.muted&&
a.video.setAttribute("muted",d.options.muted);void 0!==a.elementID?(document.getElementById(a.elementID).appendChild(a.div),a.container=document.getElementById(a.elementID)):(document.body.appendChild(a.div),a.container=document.body);a.parentNode=a.div.parentNode;a.div.appendChild(a.loader);a.div.appendChild(a.video);a.containerWidth=0;a.containerHeight=0;a.resize=setInterval(function(){var b=a.container.offsetWidth,c=a.container.offsetHeight;if(d.stream.screen){Woogeen.Logger.debug("Screen!");if(b*
0.75<c){a.video.style.width=b+"px";a.video.style.height=0.75*b+"px";a.video.style.top=-(0.75*b/2-c/2)+"px";a.video.style.left="0px"}else{a.video.style.height=c+"px";a.video.style.width=4/3*c+"px";a.video.style.left=-(4/3*c/2-b/2)+"px";a.video.style.top="0px"}}else if(b!==a.containerWidth||c!==a.containerHeight)if(b*0.75>c){a.video.style.width=b+"px";a.video.style.height=0.75*b+"px";a.video.style.top=-(0.75*b/2-c/2)+"px";a.video.style.left="0px"}else{a.video.style.height=c+"px";a.video.style.width=
4/3*c+"px";a.video.style.left=-(4/3*c/2-b/2)+"px";a.video.style.top="0px"}a.containerWidth=b;a.containerHeight=c},500);a.bar=new Woogeen.Bar({elementID:"player_"+a.id,id:a.id,stream:d.stream,video:a.video,options:a.options});a.div.onmouseover=function(){a.bar.display()};a.div.onmouseout=function(){a.bar.hide()};a.video.src=a.stream_url;return a};Woogeen=Woogeen||{};
Woogeen.Bar=function(d){var a=Woogeen.View({}),b,c;a.elementID=d.elementID;a.id=d.id;a.div=document.createElement("div");a.div.setAttribute("id","bar_"+a.id);a.bar=document.createElement("div");a.bar.setAttribute("style","width: 100%; height: 15%; max-height: 30px; position: absolute; bottom: 0; right: 0; background-color: rgba(255,255,255,0.62)");a.bar.setAttribute("id","subbar_"+a.id);a.fullscreen=document.createElement("img");a.fullscreen.setAttribute("id","fullscreen_"+a.id);a.fullscreen.setAttribute("src",
a.url+"/assets/fullscreen.png");a.fullscreen.setAttribute("style","position: absolute;");a.fullscreen.onclick=function(){a:for(var b=document.getElementById("stream"+a.id),c=0,d,g;c<e.length&&!b[d];){d="RequestFullScreen";""==e[c]&&(d=d.substr(0,1).toLowerCase()+d.substr(1));d=e[c]+d;g=typeof b[d];if("undefined"!=g){e=[e[c]];"function"==g&&b[d]();break a}c++}};var e=["webkit","moz","ms","o",""];c=function(c){"block"!==c?c="none":clearTimeout(b);a.div.setAttribute("style","width: 100%; height: 100%; position: relative; bottom: 0; right: 0; display:"+
c)};a.display=function(){c("block")};a.hide=function(){b=setTimeout(c,1E3)};document.getElementById(a.elementID).appendChild(a.div);a.div.appendChild(a.bar);a.bar.appendChild(a.fullscreen);Woogeen.Logger.debug("Screen: ",d.stream.screen);if(!d.stream.screen&&(void 0===d.options||void 0===d.options.speaker||!0===d.options.speaker))a.speaker=new Woogeen.Speaker({elementID:"subbar_"+a.id,id:a.id,stream:d.stream,video:d.video});a.display();a.hide();return a};Woogeen=Woogeen||{};
Woogeen.Speaker=function(d){var a=Woogeen.View({}),b,c,e,f=50,i=!1;a.elementID=d.elementID;a.video=d.video;a.id=d.id;a.stream=d.stream;a.div=document.createElement("div");a.div.setAttribute("style","width: 40%; height: 100%; max-width: 32px; position: absolute; right: 0;z-index:0;");a.icon=document.createElement("img");a.icon.setAttribute("id","volume_"+a.id);a.icon.setAttribute("src",a.url+"/assets/sound48.png");a.icon.setAttribute("style","width: 80%; height: 100%; position: absolute;");a.div.appendChild(a.icon);
a.stream.local?(c=function(){i=!0;a.icon.setAttribute("src",a.url+"/assets/mute48.png");a.stream.stream.getAudioTracks()[0].enabled=!1},e=function(){i=!1;a.icon.setAttribute("src",a.url+"/assets/sound48.png");a.stream.stream.getAudioTracks()[0].enabled=!0},a.icon.onclick=function(){i?e():c()}):(a.picker=document.createElement("input"),a.picker.setAttribute("id","picker_"+a.id),a.picker.type="range",a.picker.min=0,a.picker.max=100,a.picker.step=10,a.picker.value=f,a.div.appendChild(a.picker),a.video.volume=
a.picker.value/100,a.picker.oninput=function(){0<a.picker.value?(i=!1,a.icon.setAttribute("src",a.url+"/assets/sound48.png")):(i=!0,a.icon.setAttribute("src",a.url+"/assets/mute48.png"));a.video.volume=a.picker.value/100},b=function(b){a.picker.setAttribute("style","width: 32px; height: 100px; position: absolute; bottom: 90%; z-index: 1;"+a.div.offsetHeight+"px; right: 0px; -webkit-appearance: slider-vertical; display: "+b)},c=function(){i=!0;a.icon.setAttribute("src",a.url+"/assets/mute48.png");
f=a.picker.value;a.picker.value=0;a.video.volume=0},e=function(){i=!1;a.icon.setAttribute("src",a.url+"/assets/sound48.png");a.picker.value=f;a.video.volume=a.picker.value/100},a.icon.onclick=function(){i?e():c()},a.div.onmouseover=function(){b("block")},a.div.onmouseout=function(){b("none")},b("none"));document.getElementById(a.elementID).appendChild(a.div);return a};
